In [ ]:
import numpy as np
import pandas as pd

scores = np.random.randint(50, 101, size=(50, 5))
df = pd.DataFrame(scores,
             columns = ["國文","英文","地理","人文","氣候"],
             index=[f"stu{i}" for i in range(1,51)]
)
df['國文']
df['英文']
df[['國文','地理']] #只抓國文和地理的資料 
df

        國文   英文   地理   人文   氣候
stu1    80   55   94   87   85
stu2    93   82   53   50   90
stu3    50   91   89   99   66
stu4    70   80   54   70   51
stu5    62   68   50   80   84
stu6    71   50   86   91   73
stu7    91   76   52   55   69
stu8    54   73   61   64   71
stu9    79   91   97   55   67
stu10   78   62   65   52   67
stu11  100   63  100   87   74
stu12   65   83   94   80   67
stu13   94   51   82   75   77
stu14   87   83   80   87   81
stu15   80   96   76   52   66
stu16   66   51   84   93   73
stu17   69   84   56   97   95
stu18   86   74   98   57   77
stu19   54   74   55   86   79
stu20   96   50   78   91   98
stu21   66   82   83   51   55
stu22   81   55   66   62   63
stu23  100  100   61   53   80
stu24   68   52   75   64   76
stu25   51   94   84   75   68
stu26   62   80   58   78   56
stu27   62   69   89   55   96
stu28   73   66   91   91   57
stu29   76   52   75   52   94
stu30   95   70   99   84   74
stu31   96   86   85   94   56
stu32   56   76   69   95   54
stu33   69   91   72   53   74
stu34   59   56   82   89   87
stu35   55   71   67  100   69
stu36   72   79   62   57   50
stu37   78   83   79  100   51
stu38   86   98   82   62  100
stu39   90   98   86  100   58
stu40   59   52   93   69   50
stu41   88   97   74   58   76
stu42   73   91   54   91   77
stu43   61   78   67   83   58
stu44   71   95   93   63   52
stu45   64   97   69   76   85
stu46   81   62   66   88   72
stu47   86   50   50   92   85
stu48   56   80   75   89   57
stu49   62   75   90   89   87
stu50   83   69   77   92   57

In [ ]:
df.loc['stu1']
df.loc[['stu1','stu50']] #以名稱查找該名學生的資料

       國文  英文  地理  人文  氣候
stu1   80  55  94  87  85
stu50  83  69  77  92  57

In [ ]:
sum = df['國文'] + df['英文'] + df['地理'] + df['人文'] + df['氣候']
df['總分'] = sum
mean = sum / 5
df['平均'] = mean
df

        國文   英文   地理   人文   氣候   總分    平均
stu1    80   55   94   87   85  401  80.2
stu2    93   82   53   50   90  368  73.6
stu3    50   91   89   99   66  395  79.0
stu4    70   80   54   70   51  325  65.0
stu5    62   68   50   80   84  344  68.8
stu6    71   50   86   91   73  371  74.2
stu7    91   76   52   55   69  343  68.6
stu8    54   73   61   64   71  323  64.6
stu9    79   91   97   55   67  389  77.8
stu10   78   62   65   52   67  324  64.8
stu11  100   63  100   87   74  424  84.8
stu12   65   83   94   80   67  389  77.8
stu13   94   51   82   75   77  379  75.8
stu14   87   83   80   87   81  418  83.6
stu15   80   96   76   52   66  370  74.0
stu16   66   51   84   93   73  367  73.4
stu17   69   84   56   97   95  401  80.2
stu18   86   74   98   57   77  392  78.4
stu19   54   74   55   86   79  348  69.6
stu20   96   50   78   91   98  413  82.6
stu21   66   82   83   51   55  337  67.4
stu22   81   55   66   62   63  327  65.4
stu23  100  100   61   53   80  394  78.8
stu24   68   52   75   64   76  335  67.0
stu25   51   94   84   75   68  372  74.4
stu26   62   80   58   78   56  334  66.8
stu27   62   69   89   55   96  371  74.2
stu28   73   66   91   91   57  378  75.6
stu29   76   52   75   52   94  349  69.8
stu30   95   70   99   84   74  422  84.4
stu31   96   86   85   94   56  417  83.4
stu32   56   76   69   95   54  350  70.0
stu33   69   91   72   53   74  359  71.8
stu34   59   56   82   89   87  373  74.6
stu35   55   71   67  100   69  362  72.4
stu36   72   79   62   57   50  320  64.0
stu37   78   83   79  100   51  391  78.2
stu38   86   98   82   62  100  428  85.6
stu39   90   98   86  100   58  432  86.4
stu40   59   52   93   69   50  323  64.6
stu41   88   97   74   58   76  393  78.6
stu42   73   91   54   91   77  386  77.2
stu43   61   78   67   83   58  347  69.4
stu44   71   95   93   63   52  374  74.8
stu45   64   97   69   76   85  391  78.2
stu46   81   62   66   88   72  369  73.8
stu47   86   50   50   92   85  363  72.6
stu48   56   80   75   89   57  357  71.4
stu49   62   75   90   89   87  403  80.6
stu50   83   69   77   92   57  378  75.6

In [4]:
df.iloc[-10:,:5]

       國文  英文  地理  人文  氣候
stu41  88  97  74  58  76
stu42  73  91  54  91  77
stu43  61  78  67  83  58
stu44  71  95  93  63  52
stu45  64  97  69  76  85
stu46  81  62  66  88  72
stu47  86  50  50  92  85
stu48  56  80  75  89  57
stu49  62  75  90  89  87
stu50  83  69  77  92  57